net = input('Venit:')
int_net = int(net)
print('Recomandarile noastre:')
print('Cheltuieli uzuale:', int_net * 50 * (1 / 100))
print('Recreere:', int_net * 30 * (1 / 100))
print('Economii si datorii:', int_net * 20 * (1 / 100))
